# Generated by Django 3.2.16 on 2024-05-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0005_auto_20240513_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
